spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:./data/data

  # http://localhost:8080/h2-console
  # JDBC URL: jdbc:h2:./data/data

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

